2018-04-03 02:12:58,904 ERROR: Exception on /reset_password_request [POST] [in c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask\app.py:1560
Traceback (most recent call last):
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask_mail.py", line 192, in send
    message.rcpt_options)
  File "c:\users\rh laptop\appdata\local\programs\python\python36-32\Lib\smtplib.py", line 852, in sendmail
    self.ehlo_or_helo_if_needed()
  File "c:\users\rh laptop\appdata\local\programs\python\python36-32\Lib\smtplib.py", line 600, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "c:\users\rh laptop\appdata\local\programs\python\python36-32\Lib\smtplib.py", line 440, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "c:\users\rh laptop\appdata\local\programs\python\python36-32\Lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "c:\users\rh laptop\appdata\local\programs\python\python36-32\Lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\RH Laptop\Documents\PythonFiles\Git_Microblog\app\routes.py", line 184, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\RH Laptop\Documents\PythonFiles\Git_Microblog\app\email.py", line 19, in send_password_reset_email
    user=user, token=token))
  File "C:\Users\RH Laptop\Documents\PythonFiles\Git_Microblog\app\email.py", line 9, in send_email
    mail.send(msg)
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "c:\users\rhlapt~1\docume~1\python~1\venvs~1\flaskw~1\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "c:\users\rh laptop\appdata\local\programs\python\python36-32\Lib\smtplib.py", line 983, in quit
    res = self.docmd("quit")
  File "c:\users\rh laptop\appdata\local\programs\python\python36-32\Lib\smtplib.py", line 420, in docmd
    self.putcmd(cmd, args)
  File "c:\users\rh laptop\appdata\local\programs\python\python36-32\Lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "c:\users\rh laptop\appdata\local\programs\python\python36-32\Lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2018-04-03 02:28:55,208 INFO: Microblog startup [in C:\Users\RH Laptop\Documents\PythonFiles\Git_Microblog\app\__init__.py:48
2018-04-03 02:32:49,510 INFO: Microblog startup [in C:\Users\RH Laptop\Documents\PythonFiles\Git_Microblog\app\__init__.py:48
